In [1]:
import torch

x = torch.FloatTensor([0.4, 0.6])[:, None]
print(x.shape)
U = torch.FloatTensor([[0.2, 0.4], [0.2, 0.6]])[None, :, :]
print(torch.cat([U[:,:,0], U[:,:,1]], dim=1))
torch.matmul(U, x[None, :, :]).squeeze(-1).shape

torch.Size([2, 1])
tensor([[ 0.2000,  0.2000,  0.4000,  0.6000]])


torch.Size([1, 2])

In [3]:
R = torch.Tensor([0, 0])[None, :]
print(R)

tensor([[ 0.,  0.]])


In [13]:
import numpy as np

def get_pmf(p):
    return p/np.sum(p)


def get_KL_div(p, q):
    epsilon = 1e-3
    p[p == 0] = epsilon
    q[q == 0] = epsilon
    return np.sum(p * np.log(p) - p * np.log(q))


def get_KL_distance(p, q):
    return 0.5 * (get_KL_div(p, q) + get_KL_div(q, p))

gold_dist = np.array([354., 82., 86., 8., 25., 1101.])[np.newaxis, :]
print(get_pmf(gold_dist))
KL_dist_baseline = get_KL_distance(get_pmf(gold_dist), get_pmf(np.array([1., 0., 0., 0., 0., 1]))[np.newaxis, :])
print("KL distance (baseline): ", KL_dist_baseline)

[[0.21376812 0.04951691 0.05193237 0.00483092 0.01509662 0.66485507]]
KL distance (baseline):  0.3624999828885832


In [10]:
np.log(1e-3)

-6.907755278982137